config/routes.rb
NestedAttributes::Application.routes.draw do
  resources :tournaments
  resources :teams
  resources :members
  resources :time_tables
  resources :schedules

end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :name, :tournament_id
  belongs_to :tournament
  has_many :members
end

app/controllers/time_tables_controller.rb
class TimeTablesController < ApplicationController
  # GET /time_tables
  # GET /time_tables.json
  def index
    @time_tables = TimeTable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_tables }
    end
  end

  # GET /time_tables/1
  # GET /time_tables/1.json
  def show
    @time_table = TimeTable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_table }
    end
  end

  # GET /time_tables/new
  # GET /time_tables/new.json
  def new
    @time_table = TimeTable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_table }
    end
  end

  # GET /time_tables/1/edit
  def edit
    if params[:member_ids].present?
      @time_table = TimeTable.find(params[:id])
      @members = @time_table.members_with_schedule params[:member_ids]
    else
      redirect_to time_table_path params[:id]
    end
  end

  # POST /time_tables
  # POST /time_tables.json
  def create
    @time_table = TimeTable.new(params[:time_table])

    respond_to do |format|
      if @time_table.save
        format.html { redirect_to @time_table, notice: 'Time table was successfully created.' }
        format.json { render json: @time_table, status: :created, location: @time_table }
      else
        format.html { render action: "new" }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_tables/1
  # PUT /time_tables/1.json
  def update
    @time_table = TimeTable.find(params[:id])

    respond_to do |format|
      if @time_table.update_attributes(params[:time_table])
        format.html { redirect_to @time_table, notice: 'Time table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_tables/1
  # DELETE /time_tables/1.json
  def destroy
    @time_table = TimeTable.find(params[:id])
    @time_table.destroy

    respond_to do |format|
      format.html { redirect_to time_tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/views/time_tables/_form.html.erb
<%= form_for(@time_table) do |f| %>
  <% if @time_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_table.errors.count, "error") %> prohibited this time_table from being saved:</h2>

      <ul>
      <% @time_table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :date %>
  <%= f.date_select :date %><br/>
  <%= f.label :team %>
  <%= f.collection_select :team_id, Team.all, :id, :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_tables/edit.html.erb
<h1>Editing time_table</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Start At</th>
    <th>End At</th>
  </tr>
  <%= form_for @time_table, url: time_table_path(@time_table) do |f| %>
    <%= f.fields_for :members, @members do |mf| %>
      <tr>
        <td><%= mf.object.name %></td>
        <%= mf.fields_for :schedules, mf.object.schedule_in_table do |sf| %>
          <td>
            <%= sf.hidden_field :id %>
            <%= sf.hidden_field :time_table_id %>
            <%= sf.hidden_field :date %>
            <%= sf.time_select :start_at %>
          </td>
          <td><%= sf.time_select :end_at %></td>
        <% end %>
      </tr>
    <% end %>
    <tr><td colspan="3"><%= f.submit %></td></tr>
  <% end %>
</table>

<%= link_to 'Show', @time_table %> |
<%= link_to 'Back', time_tables_path %>

app/views/time_tables/index.html.erb
<h1>Listing time_tables</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @time_tables.each do |time_table| %>
  <tr>
    <td><h2><%= time_table.date %></h2></td>
    <td><%= link_to 'Show', time_table %></td>
    <td><%= link_to 'Edit', edit_time_table_path(time_table) %></td>
    <td><%= link_to 'Destroy', time_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Time table', new_time_table_path %>

app/views/time_tables/new.html.erb
<h1>New time_table</h1>

<%= render 'form' %>

<%= link_to 'Back', time_tables_path %>

app/views/time_tables/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @time_table.date %></h2>

<%= form_for @time_table, url: edit_time_table_path(@time_table), method: :get do |f| %>
  <% @time_table.members.each do |member| %>
    <%= check_box_tag "member_ids[]", member.id %><%= member.name %><br/>
  <% end %>
  <%= f.submit "Edit those Players"%>
<% end %>
<%= link_to 'Edit', edit_time_table_path(@time_table) %> |
<%= link_to 'Back', time_tables_path %>