config/routes.rb
NestedAttributes::Application.routes.draw do
  resources :tournaments
  resources :teams
  resources :members
  resources :time_tables
  resources :schedules

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :name, :team_id, :schedules_attributes
  belongs_to :team
  has_many :schedules

  # This attr is using to call the schedule of TimeTable through member
  attr_accessor :schedule_in_table

  accepts_nested_attributes_for :schedules

  # Rewrite the setter of nested attributes at middle object
  def schedules_attributes=(attributes)
    # This is the only one logic block
    attributes.values.each do |schedule|
      if schedule["id"].blank? || schedule["time_table_id"].blank?
        # Rescue errors of creating parent object here
        xtb = TimeTable.where(date: schedule["date"],
                              team_id: self.team.id)
          .first_or_create(date: schedule["date"].to_date,
                           team_id: self.team.id)
        # reject this current set of objects here, then next
        next unless xtb
        xschedule = xtb.schedules.select{|sc| sc.member_id == self.id}.first
        schedule.merge!("id" => xschedule.try(:id),
                        "time_table_id" => xtb.id)
      end
    end
    # Call this method for a has_many association
    assign_nested_attributes_for_collection_association(:schedules, attributes)
    # Call assign_nested_attributes_for_one_on_one_association if has_one
    # Refs: lib/activerecord/nested_attributes.rb:333
  end

  # The initializer that called from the initializer of middle object
  # to load children objects
  def load_schedule_in_day xday
    self.schedule_in_table = Array(self.schedules
      .select{|s| s.date == xday}.first || schedules.new(date: xday))
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :team %>
  <%= f.collection_select :team_id, Team.all, :id, :name %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><h2><%= member.name %></h2></td>
    <td><%= member.team.name %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @member.name %></h2>-<%= @member.team.name %><br/>
<table>
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Start At</th>
    <th>End At</th>
  </tr>
  <% @member.schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.id %></td>
      <td><%= schedule.date %></td>
      <td><%= schedule.start_at %></td>
      <td><%= schedule.end_at %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>